services:
  - type: web
    name: n8n-agentetelegram
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_HOST
        value: ${RENDER_EXTERNAL_HOSTNAME}
      - key: N8N_EDITOR_BASE_URL
        value: https://${RENDER_EXTERNAL_HOSTNAME}
      - key: WEBHOOK_URL
        value: https://${RENDER_EXTERNAL_HOSTNAME}
